env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://loonar.cloud
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://loonar.cloud
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: loonar.cloud-202511142217.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
